*&---------------------------------------------------------------------*
*& Modulpool SAPBC414_TRAVELAG_T
*&---------------------------------------------------------------------*


INCLUDE ZTRAVELAG_A01_TOP.
*INCLUDE BC414_TRAVELAG_TTOP.
INCLUDE ZTRAVELAG_A01_F01.
*INCLUDE BC414_TRAVELAG_TF01.
INCLUDE ZTRAVELAG_A01_O01.
*INCLUDE BC414_TRAVELAG_TO01.
INCLUDE ZTRAVELAG_A01_I01.
*INCLUDE BC414_TRAVELAG_TI01.
INCLUDE ZTRAVELAG_A01_E01.
*INCLUDE BC414_TRAVELAG_TE01.
